apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alb-ingress-controller
    spec:
      serviceAccountName: alb-ingress-controller
      containers:
        - name: alb-ingress-controller
          args:
            - --watch-namespace=kube-system
            - --ingress-class=alb
            - --cluster-name=dev-cluster
            - --aws-vpc-id=vpc-0abc244c4456f31a9
            - --aws-region=ap-south-1
            - --aws-api-debug=true
          image: docker.io/amazon/aws-load-balancer-controller:v2.3.1
