apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster2  # Ensure the cluster name meets AWS naming constraints
  region: ap-south-1

vpc:
  subnets:
    public:
      ap-south-1a:
        id: subnet-011008224842cc43f
      ap-south-1b:
        id: subnet-048ab2e2d9705ea44
managednodeGroups:
  - name: eks-nodegrp2
    minSize: 2
    maxSize: 3
    instancesDistribution:
      maxPrice: 0.03
      instanceTypes: ["c5a.large"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    labels:
      role: worker
    tags:
      nodegroup-role: worker
    iam:
      instanceRoleARN: arn:aws:iam::265993919837:role/EKSNodeGroupRole
      withAddonPolicies:
        externalDNS: true
        certManager: true
    ssh:
      allow: true
      publicKeyName: mis  # Ensure 'mis' is a valid key in the specified region
