apiVersion: v1
kind: Service
spec:
  selector:
    service.beta.kubernetes.io/do-loadbalancer-protocol
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-d
  name: jenkins-s
  namespace: apps
spec:
  ports:
  - name: 5678-8080
    port: 5678
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins-d
  type: LoadBalancer
status:
  loadBalancer: {}
